name: CI build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test-linux:
    runs-on: ubuntu-latest
    name: ( Linux Build ${{ matrix.cfg_release_channel }})
    strategy:
      matrix:
        cfg_release_channel: [ nightly, stable]

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/rust-build-test
      with:
        target: x86_64-unknown-linux-gnu
        channel: ${{ matrix.cfg_release_channel }}

  build-test-macos:
    runs-on: macos-latest
    name: ( MacOs build ${{ matrix.cfg_release_channel }})
    strategy:
      matrix:
        cfg_release_channel: [ nightly, stable]

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/rust-build-test
      with:
        target: x86_64-apple-darwin
        channel: ${{ matrix.cfg_release_channel }}
